### ISSUE TITLE
Issue with GEM_PATH when using emacs robe

### ISSUE THREAD

**Issue by Immortalin** [JeanMertz/chruby-fish#21]
I am using the spacemacs configuration layer with emacs. However, I am getting the following error when running `M-x robe-start`:
```sh
/home/immortalin/.rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/dependency.rb:318:in `to_specs': Could not find 'bundler' (>= 0.a) among 9 total gem(s) (Gem::LoadError)
Checked in 'GEM_PATH=/home/immortalin/.gem/ruby/2.2.0:/home/immortalin/.rubies/ruby-2.2.3/lib/ruby/gems/2.2.0', execute `gem env` for more information
	from /home/immortalin/.rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/dependency.rb:327:in `to_spec'
	from /home/immortalin/.rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_gem.rb:64:in `gem'
	from /home/immortalin/.gem/ruby/2.2.3/bin/bundle:22:in `<main>'

Process rails exited abnormally with code 1
```

Running `gem env` gives the following:

```sh
RubyGems Environment:
  - RUBYGEMS VERSION: 2.5.0
  - RUBY VERSION: 2.2.3 (2015-08-18 patchlevel 173) [i686-linux]
  - INSTALLATION DIRECTORY: /home/immortalin/.gem/ruby/2.2.3
  - USER INSTALLATION DIRECTORY: /home/immortalin/.gem/ruby/2.2.0
  - RUBY EXECUTABLE: /home/immortalin/.rubies/ruby-2.2.3/bin/ruby
  - EXECUTABLE DIRECTORY: /home/immortalin/.gem/ruby/2.2.3/bin
  - SPEC CACHE DIRECTORY: /home/immortalin/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /home/immortalin/.rubies/ruby-2.2.3/etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86-linux
  - GEM PATHS:
     - /home/immortalin/.gem/ruby/2.2.3
     - /home/immortalin/.rubies/ruby-2.2.3/lib/ruby/gems/2.2.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /home/immortalin/.gem/ruby/2.2.3/bin
     - /home/immortalin/.rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/bin
     - /home/immortalin/.rubies/ruby-2.2.3/bin
     - /home/immortalin/bin
     - /usr/local/sbin
     - /usr/local/bin
     - /usr/sbin
     - /usr/bin
     - /sbin
     - /bin
     - /usr/games
     - /usr/local/games
     - /usr/local/go/bin
     - /home/immortalin/Development/Go/bin
     - ~/bin
     - /opt/apache-maven-3.3.3/bin
     - ~/npm-global/bin
     - 
     - /usr/lib/jvm/java-8-oracle/bin
     - /usr/lib/jvm/java-8-oracle/db/bin
     - /usr/lib/jvm/java-8-oracle/jre/bin
```

This is my `config.fish`:
```sh
fish_vi_mode
source /usr/local/share/chruby/chruby.fish
chruby 2.2.3
source ~/.fishmarks/marks.fish

```

**Comment by JeanMertz** [comment]
Are you sure Bundler is installed for that specific Ruby version? Please run:

```bash
chruby 2.2.3
gem list bundler
```
